/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CountriesList {
    }
    interface CovidStatististicsCountryByDate {
        "Parameter": string;
    }
}
declare global {
    interface HTMLCountriesListElement extends Components.CountriesList, HTMLStencilElement {
    }
    var HTMLCountriesListElement: {
        prototype: HTMLCountriesListElement;
        new (): HTMLCountriesListElement;
    };
    interface HTMLCovidStatististicsCountryByDateElement extends Components.CovidStatististicsCountryByDate, HTMLStencilElement {
    }
    var HTMLCovidStatististicsCountryByDateElement: {
        prototype: HTMLCovidStatististicsCountryByDateElement;
        new (): HTMLCovidStatististicsCountryByDateElement;
    };
    interface HTMLElementTagNameMap {
        "countries-list": HTMLCountriesListElement;
        "covid-statististics-country-by-date": HTMLCovidStatististicsCountryByDateElement;
    }
}
declare namespace LocalJSX {
    interface CountriesList {
    }
    interface CovidStatististicsCountryByDate {
        "Parameter"?: string;
    }
    interface IntrinsicElements {
        "countries-list": CountriesList;
        "covid-statististics-country-by-date": CovidStatististicsCountryByDate;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "countries-list": LocalJSX.CountriesList & JSXBase.HTMLAttributes<HTMLCountriesListElement>;
            "covid-statististics-country-by-date": LocalJSX.CovidStatististicsCountryByDate & JSXBase.HTMLAttributes<HTMLCovidStatististicsCountryByDateElement>;
        }
    }
}
